#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean all
# Parse arguments for library compilation
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#wmake $targetType intermediate
wmake libso
#------------------------------------------------------------------------------
